### ISSUE TITLE
库导不进去啊，需要什么特别的配置么

### ISSUE THREAD

**Issue by i91h1r** [TruthKeeper/MediaPicker#2]
如题

**Comment by TruthKeeper** [comment]
Library依赖这些：

    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.1.6'
    compile 'top.zibin:Luban:1.0.8'
    compile 'com.github.chrisbanes:PhotoView:1.3.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'

app依赖这些：

    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'

这个是自己的练手项目，顺手在根目录.gradle加了支持Lambda表达式⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄
